import {
  RichTextBlock,
  ImageBlock,
  VideoBlock,
  CarouselBlock,
  PullQuoteBlock,
  CalloutBlock,
  EmbedBlock,
  SideBySideBlock,
  DropcapParagraphBlock,
  TimelineBlock,
  QuoteWithImageBlock,
  AuthorBioBlock,
  AdsBlock,
  FootnotesBlock,
  InteractivePollBlock,
} from './index'

export const articleBlocks = [
  RichTextBlock,
  ImageBlock,
  VideoBlock,
  CarouselBlock,
  PullQuoteBlock,
  CalloutBlock,
  EmbedBlock,
  SideBySideBlock,
  DropcapParagraphBlock,
  TimelineBlock,
  QuoteWithImageBlock,
  AuthorBioBlock,
  AdsBlock,
  FootnotesBlock,
  InteractivePollBlock,
]
