// src/collections/Engagement/Notifications.ts

import type { CollectionConfig } from 'payload'
import * as AccessControl from '@/access/control'

/* ============================================================
   OWNERSHIP HELPER (PAYLOAD SAFE)
============================================================ */

const isNotificationRecipient = (req: any, doc: any): boolean => {
  if (!req?.user || !doc) return false

  const uid = String(req.user.id)
  const recipientId =
    typeof doc.recipient === 'object' ? String(doc.recipient?.id) : String(doc.recipient)

  return uid === recipientId
}

/* ============================================================
   COLLECTION
============================================================ */

export const Notifications: CollectionConfig = {
  slug: 'notifications',

  admin: {
    useAsTitle: 'title',
    group: 'Engagement',
    defaultColumns: ['title', 'type', 'recipient', 'isRead', 'createdAt'],
  },

  /* -----------------------------------------------------------
     ACCESS CONTROL (DELIVERY SAFE)
  ----------------------------------------------------------- */
  access: {
    /**
     * READ
     * - Recipient
     * - Admin override
     */
    read: ({ req, doc }: any) => {
      if (AccessControl.isAdminRole(req)) return true
      return isNotificationRecipient(req, doc)
    },

    /**
     * CREATE
     * - System / Admin only
     * - Notifications are generated by automations
     */
    create: AccessControl.isAdmin,

    /**
     * UPDATE
     * - Recipient (read/archive flags)
     * - Admin override
     */
    update: ({ req, doc }: any) => {
      if (AccessControl.isAdminRole(req)) return true
      return isNotificationRecipient(req, doc)
    },

    /**
     * DELETE
     * - Admin only
     */
    delete: AccessControl.isAdmin,
  },

  timestamps: true,

  /* -----------------------------------------------------------
     FIELDS
  ----------------------------------------------------------- */
  fields: [
    /* ------------------------------------------------------
     * NOTIFICATION META
     ------------------------------------------------------ */
    {
      name: 'title',
      type: 'text',
      required: true,
      admin: {
        description: 'Short notification headline.',
      },
    },

    {
      name: 'message',
      type: 'textarea',
      required: true,
      admin: {
        description: 'The notification content shown to the user.',
      },
    },

    {
      name: 'type',
      type: 'select',
      required: true,
      defaultValue: 'general',
      options: [
        { label: 'General', value: 'general' },
        { label: 'Comment', value: 'comment' },
        { label: 'Reply', value: 'reply' },
        { label: 'Review', value: 'review' },
        { label: 'Reaction', value: 'reaction' },
        { label: 'Follow', value: 'follow' },
        { label: 'Message', value: 'message' },
        { label: 'Release Alert', value: 'release' },
        { label: 'Playlist Update', value: 'playlist' },
        { label: 'Article Published', value: 'article' },
        { label: 'Show Update', value: 'show' },
        { label: 'Episode Release', value: 'episode' },
        { label: 'Podcast Release', value: 'podcast' },
        { label: 'Chart Update', value: 'chart' },
        { label: 'System Alert', value: 'system' },
      ],
    },

    /* ------------------------------------------------------
     * DELIVERY STATE (RECIPIENT MUTABLE)
     ------------------------------------------------------ */
    {
      name: 'isRead',
      type: 'checkbox',
      defaultValue: false,
    },

    {
      name: 'isArchived',
      type: 'checkbox',
      defaultValue: false,
    },

    {
      name: 'urgent',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        description: 'Mark notification as high priority.',
      },
    },

    /* ------------------------------------------------------
     * ACTOR
     ------------------------------------------------------ */
    {
      name: 'actor',
      type: 'relationship',
      relationTo: 'profiles',
      admin: {
        description: 'User who triggered the notification.',
      },
    },

    /* ------------------------------------------------------
     * RECIPIENT (LOCKED)
     ------------------------------------------------------ */
    {
      name: 'recipient',
      type: 'relationship',
      relationTo: 'profiles',
      required: true,
      admin: {
        readOnly: true,
        description: 'User who receives the notification.',
      },
    },

    /* ------------------------------------------------------
     * MEDIA ATTACHMENTS
     ------------------------------------------------------ */
    {
      name: 'mediaType',
      type: 'select',
      admin: {
        description: 'Optional — attach media to this notification.',
      },
      options: [
        'tracks',
        'albums',
        'films',
        'podcasts',
        'podcast-episodes',
        'shows',
        'episodes',
        'vod',
        'articles',
        'reviews',
        'playlists',
        'charts',
      ].map((m) => ({ label: m, value: m })),
    },

    {
      name: 'mediaItem',
      type: 'relationship',
      relationTo: [
        'tracks',
        'albums',
        'films',
        'podcasts',
        'podcast-episodes',
        'shows',
        'episodes',
        'vod',
        'articles',
        'reviews',
        'playlists',
        'charts',
      ],
      admin: {
        description: 'Attach specific content this notification refers to.',
        condition: (data) => !!data?.mediaType,
      },
    },

    /* ------------------------------------------------------
     * CTA
     ------------------------------------------------------ */
    {
      name: 'ctaLabel',
      type: 'text',
      admin: {
        description: "Button label, e.g. 'View', 'Reply'.",
      },
    },
    {
      name: 'ctaUrl',
      type: 'text',
      admin: {
        description: 'Destination URL when CTA is clicked.',
      },
    },

    /* ------------------------------------------------------
     * METADATA
     ------------------------------------------------------ */
    {
      name: 'metadata',
      type: 'json',
      admin: {
        description: 'Custom data passed to the frontend.',
      },
    },

    /* ------------------------------------------------------
     * AUDIT (LOCKED)
     ------------------------------------------------------ */
    {
      name: 'createdBy',
      type: 'relationship',
      relationTo: 'users',
      admin: { readOnly: true },
    },
    {
      name: 'updatedBy',
      type: 'relationship',
      relationTo: 'users',
      admin: { readOnly: true },
    },
  ],

  /* -----------------------------------------------------------
     HOOKS
  ----------------------------------------------------------- */
  hooks: {
    beforeChange: [
      ({ data, req, operation }) => {
        if (req?.user) {
          if (operation === 'create') {
            data.createdBy = req.user.id
          }
          data.updatedBy = req.user.id
        }
        return data
      },
    ],
  },
}

export default Notifications
