// src/collections/Events/Tickets.ts

import type { CollectionConfig, FieldAccess } from 'payload'
import * as AccessControl from '@/access/control'
import { Roles } from '@/access/roles'

/* ============================================================
   FIELD ACCESS HELPERS (BOOLEAN ONLY)
============================================================ */

/**
 * Admin-only fields (status, QR, system fields)
 */
const adminOnly: FieldAccess = ({ req }) => Boolean(req?.user && AccessControl.isAdminRole(req))

/**
 * Owner or attendee can update limited fields (notes only)
 */
const ownerOrAttendee: FieldAccess = ({ req, doc }) => {
  if (!req?.user || !doc) return false
  const uid = String(req.user.id)

  const purchaserId =
    doc.purchaser &&
    (typeof doc.purchaser === 'object' ? String(doc.purchaser.id) : String(doc.purchaser))

  const attendeeId =
    doc.attendee &&
    (typeof doc.attendee === 'object' ? String(doc.attendee.id) : String(doc.attendee))

  return uid === purchaserId || uid === attendeeId
}

/* ============================================================
   COLLECTION
============================================================ */

export const Tickets: CollectionConfig = {
  slug: 'tickets',

  admin: {
    useAsTitle: 'ticketNumber',
    group: 'Events',
    defaultColumns: ['ticketNumber', 'event', 'ticketType', 'status'],
  },

  /* -----------------------------------------------------------
     ACCESS CONTROL (COLLECTION LEVEL)
     NOTE: No `doc` here (Payload v3 rule)
  ----------------------------------------------------------- */
  access: {
    /**
     * Read: logged-in users (field-level controls handle ownership)
     */
    read: ({ req }) => Boolean(req?.user),

    /**
     * Create: staff+ or system (orders, purchases)
     */
    create: ({ req }) => Boolean(req?.user && AccessControl.hasRoleAtOrAbove(req, Roles.STAFF)),

    /**
     * Update: staff+ only (tickets are credentials)
     */
    update: ({ req }) => Boolean(req?.user && AccessControl.hasRoleAtOrAbove(req, Roles.STAFF)),

    /**
     * Delete: admin only (emergency remediation)
     */
    delete: ({ req }) => Boolean(req?.user && AccessControl.hasRoleAtOrAbove(req, Roles.ADMIN)),
  },

  timestamps: true,

  fields: [
    /* ---------------- IDENTIFICATION ---------------- */
    {
      name: 'ticketNumber',
      type: 'text',
      unique: true,
      index: true,
      admin: { description: 'Generated by backend upon purchase.' },
      access: { update: adminOnly },
    },

    /* ---------------- RELATIONSHIPS ---------------- */
    {
      name: 'event',
      type: 'relationship',
      relationTo: 'events',
      required: true,
      access: { update: adminOnly },
    },

    {
      name: 'ticketType',
      type: 'relationship',
      relationTo: 'ticket-types',
      required: true,
      access: { update: adminOnly },
    },

    {
      name: 'order',
      type: 'relationship',
      relationTo: 'orders',
      admin: { description: 'Order that generated this ticket.' },
      access: { update: adminOnly },
    },

    {
      name: 'purchaser',
      type: 'relationship',
      relationTo: 'profiles',
      admin: { description: 'Profile who paid for the ticket.' },
      access: { update: adminOnly },
    },

    {
      name: 'attendee',
      type: 'relationship',
      relationTo: 'profiles',
      admin: { description: 'Actual attendee (can differ from purchaser).' },
      access: { update: adminOnly },
    },

    /* ---------------- STATUS & CHECK-IN ---------------- */
    {
      type: 'row',
      fields: [
        {
          name: 'status',
          type: 'select',
          defaultValue: 'issued',
          access: { update: adminOnly },
          options: [
            { label: 'Reserved', value: 'reserved' },
            { label: 'Issued', value: 'issued' },
            { label: 'Checked In', value: 'checked-in' },
            { label: 'Cancelled', value: 'cancelled' },
            { label: 'Refunded', value: 'refunded' },
            { label: 'Transferred', value: 'transferred' },
          ],
          admin: { width: '50%' },
        },
        {
          name: 'checkInMethod',
          type: 'select',
          access: { update: adminOnly },
          options: [
            { label: 'None', value: 'none' },
            { label: 'Scanner', value: 'scanner' },
            { label: 'Manual', value: 'manual' },
          ],
          admin: { width: '50%' },
        },
      ],
    },

    {
      name: 'checkedInAt',
      type: 'date',
      access: { update: adminOnly },
    },

    /* ---------------- SEATING ---------------- */
    {
      name: 'seat',
      type: 'group',
      admin: { description: 'Optional reserved seating info.' },
      access: { update: adminOnly },
      fields: [
        { name: 'section', type: 'text' },
        { name: 'row', type: 'text' },
        { name: 'seatNumber', type: 'text' },
      ],
    },

    /* ---------------- SCANNING ---------------- */
    {
      name: 'qrCode',
      type: 'text',
      admin: {
        description: 'QR / barcode content encoded for scan.',
      },
      access: { update: adminOnly },
    },

    /* ---------------- USER NOTES ---------------- */
    {
      name: 'notes',
      type: 'textarea',
      access: { update: ownerOrAttendee },
    },

    /* ---------------- AUDIT ---------------- */
    {
      name: 'createdBy',
      type: 'relationship',
      relationTo: 'users',
      access: { update: () => false },
      admin: { readOnly: true },
    },
    {
      name: 'updatedBy',
      type: 'relationship',
      relationTo: 'users',
      access: { update: () => false },
      admin: { readOnly: true },
    },
  ],

  /* -----------------------------------------------------------
     HOOKS
  ----------------------------------------------------------- */
  hooks: {
    beforeChange: [
      ({ data, req, operation }) => {
        if (req.user) {
          if (operation === 'create') data.createdBy = req.user.id
          data.updatedBy = req.user.id
        }

        return data
      },
    ],
  },
}

export default Tickets
