import type { CollectionConfig } from 'payload'

export const Tickets: CollectionConfig = {
  slug: 'tickets',

  admin: {
    useAsTitle: 'ticketNumber',
    group: 'Events',
    defaultColumns: ['ticketNumber', 'event', 'ticketType', 'status'],
  },

  access: {
    read: ({ req }) => Boolean(req.user),
    create: ({ req }) => Boolean(req.user),
    update: ({ req }) => Boolean(req.user),
    delete: ({ req }) => Boolean(req.user?.roles?.includes('admin')),
  },

  timestamps: true,

  fields: [
    {
      name: 'ticketNumber',
      type: 'text',
      unique: true,
      index: true,
      admin: { description: 'Generated by backend upon purchase.' },
    },

    {
      name: 'event',
      type: 'relationship',
      relationTo: 'events',
      required: true,
    },

    {
      name: 'ticketType',
      type: 'relationship',
      relationTo: 'ticket-types',
      required: true,
    },

    {
      name: 'order',
      type: 'relationship',
      relationTo: 'orders',
      admin: { description: 'Order that generated this ticket.' },
    },

    {
      name: 'purchaser',
      type: 'relationship',
      relationTo: 'profiles',
      admin: { description: 'Profile who paid for the ticket.' },
    },

    {
      name: 'attendee',
      type: 'relationship',
      relationTo: 'profiles',
      admin: { description: 'Actual attendee (can differ from purchaser).' },
    },

    {
      type: 'row',
      fields: [
        {
          name: 'status',
          type: 'select',
          defaultValue: 'issued',
          options: [
            { label: 'Reserved', value: 'reserved' },
            { label: 'Issued', value: 'issued' },
            { label: 'Checked In', value: 'checked-in' },
            { label: 'Cancelled', value: 'cancelled' },
            { label: 'Refunded', value: 'refunded' },
            { label: 'Transferred', value: 'transferred' },
          ],
          admin: { width: '50%' },
        },
        {
          name: 'checkInMethod',
          type: 'select',
          options: [
            { label: 'None', value: 'none' },
            { label: 'Scanner', value: 'scanner' },
            { label: 'Manual', value: 'manual' },
          ],
          admin: { width: '50%' },
        },
      ],
    },

    {
      name: 'checkedInAt',
      type: 'date',
    },

    {
      name: 'seat',
      type: 'group',
      admin: { description: 'Optional reserved seating info.' },
      fields: [
        { name: 'section', type: 'text' },
        { name: 'row', type: 'text' },
        { name: 'seatNumber', type: 'text' },
      ],
    },

    {
      name: 'qrCode',
      type: 'text',
      admin: {
        description: 'QR / barcode content encoded for scan.',
      },
    },

    {
      name: 'notes',
      type: 'textarea',
    },

    {
      name: 'createdBy',
      type: 'relationship',
      relationTo: 'users',
      admin: { readOnly: true },
    },
    {
      name: 'updatedBy',
      type: 'relationship',
      relationTo: 'users',
      admin: { readOnly: true },
    },
  ],

  hooks: {
    beforeChange: [
      ({ data, req, operation }) => {
        if (req.user) {
          if (operation === 'create') data.createdBy = req.user.id
          data.updatedBy = req.user.id
        }
        return data
      },
    ],
  },
}
