import type { CollectionConfig } from 'payload'

export const Orders: CollectionConfig = {
  slug: 'orders',

  admin: {
    useAsTitle: 'orderNumber',
    group: 'Events',
    defaultColumns: ['orderNumber', 'status', 'purchaser', 'total'],
  },

  access: {
    read: ({ req }) => Boolean(req.user),
    create: ({ req }) => Boolean(req.user),
    update: ({ req }) => Boolean(req.user),
    delete: ({ req }) => Boolean(req.user?.roles?.includes('admin')),
  },

  timestamps: true,

  fields: [
    {
      name: 'orderNumber',
      type: 'text',
      unique: true,
      index: true,
      admin: { description: 'Generated by backend / Stripe metadata.' },
    },

    {
      name: 'status',
      type: 'select',
      defaultValue: 'pending',
      options: [
        { label: 'Pending', value: 'pending' },
        { label: 'Paid', value: 'paid' },
        { label: 'Cancelled', value: 'cancelled' },
        { label: 'Refunded', value: 'refunded' },
      ],
    },

    {
      name: 'purchaser',
      type: 'relationship',
      relationTo: 'profiles',
      required: true,
    },

    {
      type: 'row',
      fields: [
        { name: 'email', type: 'text', admin: { width: '50%' } },
        { name: 'phone', type: 'text', admin: { width: '50%' } },
      ],
    },

    {
      name: 'items',
      type: 'array',
      labels: { singular: 'Item', plural: 'Items' },
      fields: [
        {
          name: 'ticketType',
          type: 'relationship',
          relationTo: 'ticket-types',
          required: true,
        },
        {
          name: 'event',
          type: 'relationship',
          relationTo: 'events',
          required: true,
        },
        {
          type: 'row',
          fields: [
            { name: 'quantity', type: 'number', required: true, admin: { width: '33%' } },
            { name: 'unitPrice', type: 'number', required: true, admin: { width: '33%' } },
            { name: 'totalPrice', type: 'number', required: true, admin: { width: '33%' } },
          ],
        },
      ],
    },

    {
      type: 'row',
      fields: [
        { name: 'subtotal', type: 'number', admin: { width: '33%' } },
        { name: 'fees', type: 'number', admin: { width: '33%' } },
        { name: 'total', type: 'number', required: true, admin: { width: '33%' } },
      ],
    },

    {
      name: 'currency',
      type: 'select',
      defaultValue: 'USD',
      options: [
        { label: 'USD', value: 'USD' },
        { label: 'EUR', value: 'EUR' },
        { label: 'GBP', value: 'GBP' },
      ],
    },

    {
      name: 'paymentProvider',
      type: 'select',
      defaultValue: 'stripe',
      options: [
        { label: 'Stripe', value: 'stripe' },
        { label: 'None / Manual', value: 'none' },
      ],
    },
    { name: 'providerSessionId', type: 'text' },
    { name: 'providerPaymentIntentId', type: 'text' },

    {
      name: 'paidAt',
      type: 'date',
    },
    {
      name: 'cancelledAt',
      type: 'date',
    },

    {
      name: 'tickets',
      type: 'relationship',
      relationTo: 'tickets',
      hasMany: true,
      admin: { readOnly: true, description: 'Tickets issued for this order.' },
    },

    {
      name: 'notes',
      type: 'textarea',
    },

    {
      name: 'createdBy',
      type: 'relationship',
      relationTo: 'users',
      admin: { readOnly: true },
    },
    {
      name: 'updatedBy',
      type: 'relationship',
      relationTo: 'users',
      admin: { readOnly: true },
    },
  ],

  hooks: {
    beforeChange: [
      ({ data, req, operation }) => {
        if (req.user) {
          if (operation === 'create') data.createdBy = req.user.id
          data.updatedBy = req.user.id
        }
        return data
      },
    ],
  },
}
