import type { CollectionConfig, Access } from 'payload'
import { isAdminRole, hasRoleAtOrAbove } from '@/access/control'
import { Roles } from '@/access/roles'

/* ============================================================
   HELPERS
============================================================ */

const isOrderOwner = (req: any, doc: any): boolean => {
  if (!req?.user || !doc?.purchaser) return false
  return String(doc.purchaser) === String(req.user.id)
}

/* ============================================================
   ACCESS RULES
============================================================ */

const canReadOrder: Access = (args: any): boolean => {
  const { req, doc } = args
  if (!req?.user) return false
  if (isAdminRole(req)) return true
  if (hasRoleAtOrAbove(req, Roles.STAFF)) return true
  return isOrderOwner(req, doc)
}

const canUpdateOrder: Access = ({ req }) => {
  if (!req?.user) return false
  return isAdminRole(req) || hasRoleAtOrAbove(req, Roles.STAFF)
}

/* ============================================================
   COLLECTION
============================================================ */

export const Orders: CollectionConfig = {
  slug: 'orders',

  admin: {
    useAsTitle: 'orderNumber',
    group: 'Events',
    defaultColumns: ['orderNumber', 'status', 'purchaser', 'total'],
  },

  access: {
    /**
     * Orders created by authenticated checkout
     */
    create: ({ req }) => Boolean(req?.user),

    /**
     * Owner + Staff + Admin
     */
    read: canReadOrder,

    /**
     * Staff + Admin only
     */
    update: canUpdateOrder,

    /**
     * Orders are immutable
     */
    delete: () => false,
  },

  timestamps: true,

  fields: [
    /* --------------------------------------------------------
       IDENTIFIERS
    -------------------------------------------------------- */
    {
      name: 'orderNumber',
      type: 'text',
      unique: true,
      index: true,
      admin: { readOnly: true, description: 'Generated by backend / Stripe metadata.' },
    },

    /* --------------------------------------------------------
       STATUS
    -------------------------------------------------------- */
    {
      name: 'status',
      type: 'select',
      defaultValue: 'pending',
      options: [
        { label: 'Pending', value: 'pending' },
        { label: 'Paid', value: 'paid' },
        { label: 'Cancelled', value: 'cancelled' },
        { label: 'Refunded', value: 'refunded' },
      ],
    },

    /* --------------------------------------------------------
       PURCHASER
    -------------------------------------------------------- */
    {
      name: 'purchaser',
      type: 'relationship',
      relationTo: 'profiles',
      required: true,
      index: true,
      admin: { readOnly: true },
    },

    {
      type: 'row',
      fields: [
        { name: 'email', type: 'text', admin: { width: '50%', readOnly: true } },
        { name: 'phone', type: 'text', admin: { width: '50%', readOnly: true } },
      ],
    },

    /* --------------------------------------------------------
       LINE ITEMS (SNAPSHOT)
    -------------------------------------------------------- */
    {
      name: 'items',
      type: 'array',
      labels: { singular: 'Item', plural: 'Items' },
      admin: { readOnly: true },
      fields: [
        {
          name: 'ticketType',
          type: 'relationship',
          relationTo: 'ticket-types',
          required: true,
        },
        {
          name: 'event',
          type: 'relationship',
          relationTo: 'events',
          required: true,
        },
        {
          type: 'row',
          fields: [
            { name: 'quantity', type: 'number', required: true, admin: { width: '33%' } },
            { name: 'unitPrice', type: 'number', required: true, admin: { width: '33%' } },
            { name: 'totalPrice', type: 'number', required: true, admin: { width: '33%' } },
          ],
        },
      ],
    },

    /* --------------------------------------------------------
       TOTALS (LOCKED)
    -------------------------------------------------------- */
    {
      type: 'row',
      fields: [
        { name: 'subtotal', type: 'number', admin: { width: '33%', readOnly: true } },
        { name: 'fees', type: 'number', admin: { width: '33%', readOnly: true } },
        { name: 'total', type: 'number', required: true, admin: { width: '33%', readOnly: true } },
      ],
    },

    /* --------------------------------------------------------
       PAYMENT
    -------------------------------------------------------- */
    {
      name: 'currency',
      type: 'select',
      defaultValue: 'USD',
      options: [
        { label: 'USD', value: 'USD' },
        { label: 'EUR', value: 'EUR' },
        { label: 'GBP', value: 'GBP' },
      ],
      admin: { readOnly: true },
    },

    {
      name: 'paymentProvider',
      type: 'select',
      defaultValue: 'stripe',
      options: [
        { label: 'Stripe', value: 'stripe' },
        { label: 'None / Manual', value: 'none' },
      ],
      admin: { readOnly: true },
    },
    { name: 'providerSessionId', type: 'text', admin: { readOnly: true } },
    { name: 'providerPaymentIntentId', type: 'text', admin: { readOnly: true } },

    { name: 'paidAt', type: 'date', admin: { readOnly: true } },
    { name: 'cancelledAt', type: 'date', admin: { readOnly: true } },

    /* --------------------------------------------------------
       TICKETS
    -------------------------------------------------------- */
    {
      name: 'tickets',
      type: 'relationship',
      relationTo: 'tickets',
      hasMany: true,
      admin: { readOnly: true, description: 'Tickets issued for this order.' },
    },

    /* --------------------------------------------------------
       INTERNAL NOTES
    -------------------------------------------------------- */
    {
      name: 'notes',
      type: 'textarea',
      admin: {
        condition: (_, { user }) =>
          Boolean(user && (isAdminRole(user) || hasRoleAtOrAbove(user, Roles.STAFF))),
      },
    },

    /* --------------------------------------------------------
       AUDIT
    -------------------------------------------------------- */
    {
      name: 'createdBy',
      type: 'relationship',
      relationTo: 'users',
      admin: { readOnly: true },
    },
    {
      name: 'updatedBy',
      type: 'relationship',
      relationTo: 'users',
      admin: { readOnly: true },
    },
  ],

  hooks: {
    beforeChange: [
      ({ data, req, operation }) => {
        if (req.user) {
          if (operation === 'create') data.createdBy = req.user.id
          data.updatedBy = req.user.id
        }
        return data
      },
    ],
  },
}
