import type { CollectionConfig, Access } from 'payload'
import * as AccessControl from '@/access/control'

/* ============================================================
   ACCESS HELPERS
============================================================ */

/**
 * Read access:
 * - Logged-in users → full access
 * - Public → API key + fetch code (safe, read-only)
 */
const canReadVariants: Access = ({ req }) => {
  if (req?.user) return true
  return AccessControl.apiLockedRead({ req } as any)
}

/**
 * Staff+ manage variants
 */
const canManageVariants: Access = ({ req }) => AccessControl.isStaff({ req })

/**
 * Admin-only hard delete
 * (variants are referenced by Media + caches)
 */
const canDeleteVariants: Access = ({ req }) => AccessControl.isAdmin({ req })

/* ============================================================
   COLLECTION
============================================================ */

export const MediaVariants: CollectionConfig = {
  slug: 'media-variants',

  labels: {
    singular: 'Media Variant',
    plural: 'Media Variants',
  },

  admin: {
    useAsTitle: 'label',
    group: 'Core',
    defaultColumns: ['label', 'parent', 'type', 'createdAt'],
    description:
      'Internal media variants generated by the system. Do not edit unless regenerating assets.',
  },

  /* -----------------------------------------------------------
     ACCESS CONTROL
  ----------------------------------------------------------- */
  access: {
    read: canReadVariants,
    create: canManageVariants,
    update: canManageVariants,
    delete: canDeleteVariants,
  },

  timestamps: true,

  /* -----------------------------------------------------------
     FIELDS
  ----------------------------------------------------------- */
  fields: [
    /* ---------------- RELATIONSHIP ---------------- */
    {
      name: 'parent',
      type: 'relationship',
      relationTo: 'media',
      required: true,
      admin: {
        description: 'Original media item this variant belongs to.',
      },
    },

    /* ---------------- METADATA ---------------- */
    {
      name: 'label',
      type: 'text',
      required: true,
      index: true,
      admin: {
        description: 'Variant label (e.g. thumbnail, square, landscape).',
      },
    },

    {
      name: 'type',
      type: 'select',
      required: true,
      defaultValue: 'image',
      options: [
        { label: 'Image', value: 'image' },
        { label: 'Video', value: 'video' },
        { label: 'Audio', value: 'audio' },
      ],
      admin: {
        description: 'Media type of this variant.',
      },
    },

    /* ---------------- FILE ---------------- */
    {
      name: 'variant',
      type: 'upload',
      relationTo: 'media',
      required: true,
      admin: {
        description: 'Generated or uploaded media variant.',
      },
    },

    /* ---------------- SYSTEM ---------------- */
    {
      name: 'generatedBy',
      type: 'select',
      defaultValue: 'system',
      options: [
        { label: 'System', value: 'system' },
        { label: 'Manual', value: 'manual' },
      ],
      admin: {
        description: 'Indicates whether this variant was auto-generated.',
      },
    },

    {
      name: 'notes',
      type: 'textarea',
      admin: {
        description: 'Internal notes (regeneration, fixes, etc.).',
      },
    },

    /* ---------------- AUDIT ---------------- */
    {
      name: 'createdBy',
      type: 'relationship',
      relationTo: 'users',
      admin: { readOnly: true },
    },

    {
      name: 'updatedBy',
      type: 'relationship',
      relationTo: 'users',
      admin: { readOnly: true },
    },
  ],

  /* -----------------------------------------------------------
     HOOKS
  ----------------------------------------------------------- */
  hooks: {
    beforeChange: [
      ({ data, req, operation }) => {
        if (!req?.user || !data) return data

        const userId = String(req.user.id)

        if (operation === 'create') {
          data.createdBy = userId
        }

        data.updatedBy = userId

        return data
      },
    ],
  },
}

export default MediaVariants
